### ISSUE TITLE
Authorization COS - KMS malformed

### ISSUE THREAD

**Issue by pauljegouic** [terraform-ibm-modules/terraform-ibm-cos#173]
Hello there,

We are facing an issue with your module, especially regarding authorization as shown below:

```
 ibm_resource_instance.kms_instance: Creating...
 2023/01/27 22:03:52 Terraform apply | module.cos.ibm_resource_instance.cos_instance[0]: Creating...
 2023/01/27 22:04:02 Terraform apply | ibm_resource_instance.kms_instance: Still creating... [10s elapsed]
 2023/01/27 22:04:02 Terraform apply | module.cos.ibm_resource_instance.cos_instance[0]: Still creating... [10s elapsed]
 2023/01/27 22:04:06 Terraform apply | ibm_resource_instance.kms_instance: Creation complete after 14s [id=crn:v1:bluemix:public:kms:eu-fr2:a/3f2cae45b0644f6d87aefcf404f5987f:ba24f111-f80e-4298-a301-ca20371a0d8d::]
 2023/01/27 22:04:06 Terraform apply | data.ibm_kms_keys.encryption_data: Reading...
 2023/01/27 22:04:06 Terraform apply | ibm_kms_key.encryption_key: Creating...
 2023/01/27 22:04:07 Terraform apply | data.ibm_kms_keys.encryption_data: Read complete after 0s [id=ba24f111-f80e-4298-a301-ca20371a0d8d]
 2023/01/27 22:04:07 Terraform apply | ibm_kms_key.encryption_key: Creation complete after 1s [id=crn:v1:bluemix:public:kms:eu-fr2:a/3f2cae45b0644f6d87aefcf404f5987f:ba24f111-f80e-4298-a301-ca20371a0d8d:key:8c87060a-6993-47b5-9ca6-1e2738973927]
 2023/01/27 22:04:08 Terraform apply | module.cos.ibm_resource_instance.cos_instance[0]: Creation complete after 16s [id=crn:v1:bluemix:public:cloud-object-storage:global:a/3f2cae45b0644f6d87aefcf404f5987f:d20bf547-6b85-4f4b-877c-1475c4bde1ee::]
 2023/01/27 22:04:08 Terraform apply | module.cos.ibm_resource_key.resource_key[0]: Creating...
 2023/01/27 22:04:08 Terraform apply | module.cos.ibm_iam_authorization_policy.policy[0]: Creating...
 2023/01/27 22:04:09 Terraform apply | module.cos.ibm_iam_authorization_policy.policy[0]: Creation complete after 1s [id=a77acd3f-d3c4-4c63-b1b5-0951bfee108d]
 2023/01/27 22:04:09 Terraform apply | module.cos.ibm_cos_bucket.cos_bucket[0]: Creating...
 2023/01/27 22:04:12 Terraform apply | module.cos.ibm_resource_key.resource_key[0]: Creation complete after 4s [id=crn:v1:bluemix:public:cloud-object-storage:global:a/3f2cae45b0644f6d87aefcf404f5987f:d20bf547-6b85-4f4b-877c-1475c4bde1ee:resource-key:3c34a882-8178-4ab8-b136-c010847e62b5]
 2023/01/27 22:04:12 Terraform apply | 
 2023/01/27 22:04:12 Terraform apply | Error: ServiceNotAuthorized: The specified COS Service Instance does not have sufficient permissions to access the resource associated with the KMS key CRN.
 2023/01/27 22:04:12 Terraform apply | 	status code: 401, request id: d32b07a0-e350-4e6a-aa86-787e467c0b4f, host id: 
 2023/01/27 22:04:12 Terraform apply | 
 2023/01/27 22:04:12 Terraform apply |   with module.cos.ibm_cos_bucket.cos_bucket[0],
 2023/01/27 22:04:12 Terraform apply |   on .terraform/modules/cos/main.tf line 76, in resource "ibm_cos_bucket" "cos_bucket":
 2023/01/27 22:04:12 Terraform apply |   76: resource "ibm_cos_bucket" "cos_bucket" {
 2023/01/27 22:04:12 Terraform apply | 
 2023/01/27 22:04:12 [1m[31mTerraform APPLY error: Terraform APPLY errorexit status 1[39m[0m
 ```
 
 We found out that your authorization resource input for the source_service_id, is not correct, it should be the GUID of the COS instance instead of ID.
 
 It results into this authorization in your IAM:
 
 
<img width="761" alt="image" src="https://user-images.githubusercontent.com/50360031/215449642-479f9dfe-6f4a-46be-872f-5d09ef0ceb1f.png">

###Proposal 

 ```hcl
 locals {
  cos_instance_id      = var.create_cos_instance == true ? tolist(ibm_resource_instance.cos_instance[*].id)[0] : var.existing_cos_instance_id
  cos_instance_guid      = var.create_cos_instance == true ? : tolist(ibm_resource_instance.cos_instance[*].guid)[0] : element(split(":",var.existing_cos_instance_id),length(split(":",var.existing_cos_instance_id)-3)
  create_access_policy = var.encryption_enabled && var.create_cos_instance
}

 # Create IAM Access Policy to allow Key protect to access COS instance
resource "ibm_iam_authorization_policy" "policy" {
  count                       = local.create_access_policy ? 1 : 0
  source_service_name         = "cloud-object-storage"
  source_resource_instance_id = local.cos_instance_guid
  target_service_name         = "kms"
  target_resource_instance_id = var.existing_key_protect_instance_guid
  roles                       = ["Reader"]
}
```

Resulting into a correct Authorization:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/50360031/215449828-78f7e669-34da-43e5-991c-9bda15b43818.png">

Let me know if you want me to do a PR.

Regards

**Comment by vburckhardt** [comment]
Hi @pauljegouic - Thanks for the ticket. Good spot. Yes, you can do a PR if you wish so 👍

**Comment by ocofaigh** [comment]
@pauljegouic Firstly, thank you very much for reporting this. The team is currently working on some automation to put in place before accepting external contributions.
I'm looking into this issue currently. I'm not actually sure its supposed to be the GUID value. From reading the ibm provider docs, it seems to specify:

[source_resource_instance_id](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/iam_authorization_policy#source_resource_instance_id) - (Optional, Forces new resource, string) The source resource instance id

Are you able to reproduce every time? I have seen this error occur intermittently in the past (possible a timing issue), but passes on retry. Can you confirm?

**Comment by ocofaigh** [comment]
I found the following update in an internal issue we opened to track this very issue:

> This has been hitting every so often. The problem is the S2S authorization is not allowing COS to access that KMS key. It is an IAM permission problem and timing issue (SLZ creates the S2S). If you re-run, it will most likely work

If re-run works, I can follow up with the IAM team on the timing issue. Please let me know

**Comment by vburckhardt** [comment]
Right, I suspect that both id and guid are allowed here, and that this issue is indeed a timing problem in some of the cases - eg: eventual consistency in replicating IAM policies across geos. If so, let's see if we could add a few second sleep after creating the s2s auth to work around the problem for now, and then in parallel see if IAM could provide some consistency SLO

**Comment by vburckhardt** [comment]
Digging deeper, I think it's a genuine issue that is not visible in the unit tests, as the account the test are run has got this wild card s2s (which should be removed).

![image](https://user-images.githubusercontent.com/16447795/217525549-47327253-530e-424f-8f30-8cb8e77e7e54.png)

**Comment by vburckhardt** [comment]
Original internal version contains a reference to guid, so seems the regression was introduced when pushing out the code? @daniel-butler-irl ?

![image](https://user-images.githubusercontent.com/16447795/217528095-3d57c2cf-6527-4ff4-8e0f-5bf180bf7537.png)

**Comment by vburckhardt** [comment]
@ocofaigh - Need to track effort to update the nuke script against the test account to also remove all s2s policies left behind. This is what caused the issue to not be caught by the unit tests. https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/173#issuecomment-1422498104

**Comment by vburckhardt** [comment]
Fixed in https://github.com/terraform-ibm-modules/terraform-ibm-cos/releases/tag/v5.3.2
