### ISSUE TITLE
Expose cos instance guid as an output

### ISSUE THREAD

**Issue by Soaib024** [terraform-ibm-modules/terraform-ibm-cos#191]
### Description

Expose cos instance guid as an output

### New or affected modules
https://github.com/terraform-ibm-modules/terraform-ibm-cos

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
This was added in https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/192
Closing
