### ISSUE TITLE
Complete example does not execute when region is set to eu-gb

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#200]
╷
│ Error: InvalidRequest: The region provided in the KMS key CRN does not provide cross region support.
│       status code: 400, request id: a6d17a58-f715-479e-bb0c-1fe53a149f00, host id: 
│ 
│   with module.cos_bucket2.ibm_cos_bucket.cos_bucket[0],
│   on ../../main.tf line 77, in resource "ibm_cos_bucket" "cos_bucket":
│   77: resource "ibm_cos_bucket" "cos_bucket" {
│

**Comment by shemau** [comment]
A temporary work around is to use eu-de or us-south region, although this is not an exhaustive list, so try others such as us-east, au-syd, jp-tok or jp-osa.

**Comment by shemau** [comment]
The complete example demonstrates cross-region support for COS. This high durability solution requires a high durability solution for the encryption key. This is currently provided by [key protect high availability](https://cloud.ibm.com/docs/key-protect?topic=key-protect-ha-dr#availability), so the example has been updated to support only these regions from v5.9.0.
