### ISSUE TITLE
Document CBR UI tag limitation in module

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#202]
### Description

The CBR UI does not currently display properly tags. The question came from one of the module consumer, and is likely to repeat, so would be good to document directly into the module README.md.

![image](https://user-images.githubusercontent.com/16447795/219204339-b8e14bea-377e-477f-9116-71d2416cb4a6.png)

### New or affected modules

- [terraform-ibm-cos](https://github.com/terraform-ibm-modules/terraform-ibm-cos)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
@SirSpidey - FYI - perhaps a task you can take.

**Comment by SirSpidey** [comment]
Discussed this with @jojustin. Waiting for confirmation from the CBR team about whether this is a UI-only issue or a larger bug.

**Comment by jojustin** [comment]
@SirSpidey Its confirmed to be a UI-only issue.  We can go ahead and document.  Also we should document that the access resource tags provided in the CBR rule should match to the access tags attached to the actual service instances.

**Comment by SirSpidey** [comment]
Documented in known issues in docs ([PR 37](https://github.com/terraform-ibm-modules/documentation/pull/37).)
