### ISSUE TITLE
Double check that access tags are indeed evaluated in the CBR rules

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#203]
### Description

There is a need to have an actual check that the tags passed in the CBR rule are indeed used. So far, I think the assumption is that they are, but I don't think this has been actually verified. Perhaps, as part of this add a tag example here: https://github.com/terraform-ibm-modules/terraform-ibm-cos/tree/main/examples

### New or affected modules

- [terraform-ibm-cos](https://github.com/terraform-ibm-modules/terraform-ibm-cos)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
Found an issue in the existing 'complete' example. It is using resource tags, whereas CBR expects access tags. Also the tag fields need to be explicitly set to an empty array if the intend is to not have tags used as part of the CBR rule.

**Comment by jojustin** [comment]
The PR for the access tags to work in 'complete' example is merged - https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/217

**Comment by jojustin** [comment]
[COS CBR with access tags test cases.pdf](https://github.com/terraform-ibm-modules/terraform-ibm-cos/files/10956312/COS.CBR.with.access.tags.test.cases.pdf)

Matching the COS instance access tags to CBR rules defined access tags works as expected.  Closing this.
