### ISSUE TITLE
Automated test suites for CBR rules

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#206]
### Description

Extracted out from original issue at https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/201 . 

`See whether we could expend the automated test suite as well to catch this type of issue - eg: trying to list the cos bucket in the instance as part of the test executing the complete example would catch this type of problem.`

**Comment by ocofaigh** [comment]
This work was done in https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/448
