### ISSUE TITLE
Add option to tie resource_key to an existing serviceId

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#212]
### Description

What:
- Current logic always creates a new ServiceId at https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/main/main.tf#L49
- There is an option to pass a reference to an existing ServiceId
- Module should take (optionally) the serviceId reference as input

**Comment by vbontempi** [comment]
PR https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/232
