### ISSUE TITLE
Add support for One-rate plan

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-cos#316]
### Description

The variable `cos_plan ` only allows `standard ` and `lite` plans however it seems there is a third plan - "One Rate":

> The One-rate plan offers large enterprises and ISVs (with multiple divisions or end-users) a predictable TCO based on one flat rate. The flat rate has built-in allowances for outbound bandwidth and operational requests. These allowances depend on the amount of storage capacity aggregated across multiple instances within a One Rate pricing region. There is no data retrieval charge.

### New or affected modules

https://github.com/terraform-ibm-modules/terraform-ibm-cos

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
Complete - closing.
