### ISSUE TITLE
Expose direct endpoint in the output

### ISSUE THREAD

**Issue by kulmannf** [terraform-ibm-modules/terraform-ibm-cos#320]
### Description

This module currently exposes the [public](https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/main/outputs.tf#L14) and [private](https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/main/outputs.tf#L9) endpoint in the output. But there are also the [direct endpoints](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-endpoints#endpoints-region) that are available from COS. Could this be added to the output as well, please?

### New or affected modules

* terraform-ibm-cos

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Looks like @argeiger has created a PR https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/368

**Comment by ocofaigh** [comment]
[PR](https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/368) merged - closing
