### ISSUE TITLE
Missing bucket_endpoint  in version 6.0.0

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#344]
bucket_endpoint was removed in version 6.0.0. However, this value is used by the provider to construct the url used to access cos management apis.

https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/service/cos/resource_ibm_cos_bucket.go#L1140

**Comment by ocofaigh** [comment]
Fixed in https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/351 which was released in 6.1.0
