### ISSUE TITLE
'encyption_enabled' field name is misleading

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#364]
Minor issue but could lead to confusion.

encryption_enabled controls whether kms encryption is enable (key protect / hpcs). If set to false, cos bucket is still encrypted but with ibm managed keys.

**Comment by maheshwarishikha** [comment]
PR - https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/378/ approved and merged.
Hence, closing the issue.
