### ISSUE TITLE
retention policy is set to enabled by default in root module

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#366]
https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/753a10a122987ec585e123c336d49e39fe79f890/variables.tf#L135

Suggest to set to false as this is going to prevent from deleting objects from cos bucket. Leave the retention enable only in the fscloud profile version at https://github.com/terraform-ibm-modules/terraform-ibm-cos/tree/main/profiles/fscloud

**Comment by Soaib024** [comment]
I am currently occupied with auditree work and I won't be able to allocate time for this issue hence un-assigning myself from the issue
