### ISSUE TITLE
endpoint_type parameter is missing from cos_bucket

### ISSUE THREAD

**Issue by jor2** [terraform-ibm-modules/terraform-ibm-cos#380]
`endpoint_type` should be defined in [`cos_bucket`](https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/main/main.tf#L87) as it is defined in [`cos_bucket1`](https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/main/main.tf#L169). When the user specifies an `endpoint_type` along with enabling encryption on their cos_bucket the `endpoint_type` will not take affect.

### Affected modules

* https://github.com/terraform-ibm-modules/terraform-ibm-cos

**Comment by shemau** [comment]
This issue is now complete and available in v6.4.1
