### ISSUE TITLE
Add support to COS module to create IAM based resource key

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-cos#485]
The COS module should support creating IAM as well as HMAC resource keys. Currently it only supports HMAC keys however IAM API Keys are the preferred method of authentication for COS as per [docs](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-service-credentials).

### Proposal:
Rename these variables (both root level module and fscloud submodule)
- `create_hmac_key` -> `create_resource_key` 
- `hmac_key_name` -> `resource_key_name`
- `hmac_key_role` -> `resource_key_role`

Create a new boolean variable called `generate-hmac-credentials` which should be used like this:
```
parameters = {
    "serviceid_crn" = var.resource_key_existing_serviceid_crn
    "HMAC"          = var.generate-hmac-credentials
  }
```
Since IAM is the recommended key type, I think we should set `generate-hmac-credentials` to false by default (make sure we mention this in the release notes, as it will attempt to destroy any existing hmac credentials and replace it with an IAM credential)

**Comment by shemau** [comment]
Reviewing the resource key the following was discovered:

Changing HMAC (in parameters) as suggested above:

HMAC = false generates a key with the following credentials block

```hcl
            "credentials": {
              "apikey": "",
              "endpoints": "",
              "iam_apikey_description": "",
              "iam_apikey_id": "",
              "iam_apikey_name": "resource-cos-key",
              "iam_role_crn": "",
              "iam_serviceid_crn": "",
              "resource_instance_id": ""
            },
```
HMAC = true generates a key with the following credentials block

```hcl
            "credentials": {
              "apikey": "",
              "cos_hmac_keys.access_key_id": "",
              "cos_hmac_keys.secret_access_key": "",
              "endpoints": "",
              "iam_apikey_description": "",
              "iam_apikey_id": "",
              "iam_apikey_name": "resource-cos-key",
              "iam_role_crn": "",
              "iam_serviceid_crn": "",
              "resource_instance_id": ""
            },
```

Which includes an API, but has an additional HMAC key in `cos_hmac_keys.access_key_id` and `cos_hmac_keys.secret_access_key`. So the resource key either has an API key, or both.

**Comment by shemau** [comment]
It has also become apparent that the parameters block is outside the lifecycle. By this I mean, that if I change just the parameter block it does NOT change the resource key. So changing `HMAC` within parameters does not remove (or add) the cos_hmac_ fields to the credentials in the state file.

Changing the `name` (via var.resource_key_name) does for the resource key to be regenerate. The default for this changed from hmac_cos_key to resource_cos_key.

With this information it possible to scope the blast radius of the change.

It will impact all users who create_resource_key (default is to create, unless overridden) and do not specify a `resource_key_name`.

It will not impact users who override `create_resource_key` to false.
It will not impact users who specify any value for `create_resource_key`

**Comment by shemau** [comment]
@ocofaigh if we leave the default for `resource_key_name` alone, I do not believe this change will impact many consumers. The scope would be limited to users who consume the resource keys credentials.cos_hmac_* values (which are not an output of the module) AND who delete and recreate the resource key.

The problem with this is that the issue will not happen during the terraform apply to make this change. It will occur at some random point in the future when the resource key is deleted and recreated. It will not be clean even then, since even if the consumer updates the property, it will not be applied to the key (due it being outside the lifecycle for terraform) until the key is again manually deleted (and recreated).

**Comment by shemau** [comment]
I think I have found the optimal solution in the terraform docs.

Using terraform_data and lifecycle to cause a resource key replacement if the values in the parameters block change.

**Comment by ocofaigh** [comment]
Included in https://github.com/terraform-ibm-modules/terraform-ibm-cos/releases/tag/v7.2.0
