### ISSUE TITLE
Variable descriptions in COS fscloud submodule need to be updated

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-cos#488]
The descriptions of the below variable in the FSCloud submodule seem to indicated they are required if 'create_cos_bucket' is true, however there is no `create_cos_bucket` variable in the FSCloud submodule. They are also not required variables at all (which I think should be correct - the user can optionally opt in).

```
variable "activity_tracker_crn" {
  type        = string
  description = "Activity tracker crn for COS bucket. Only required if 'create_cos_bucket' is true."
  default     = null
}

variable "sysdig_crn" {
  type        = string
  description = "Sysdig Monitoring crn for COS bucket. Only required if 'create_cos_bucket' is true."
  default     = null
}
```

**Comment by shemau** [comment]
🎉 This PR is included in version 7.1.4 🎉
