### ISSUE TITLE
Enable the passing of a list of resource key to create

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#527]
### Description

Current logic creates one single key (optionally) at https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/39854bc97d187cb44627763bd9d163d369637fd9/main.tf#L73 .

It would be desirable to allow creating multiple keys with different roles https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/39854bc97d187cb44627763bd9d163d369637fd9/main.tf#L81 . Essentially allow the passing of a list of roles as input to the module instead of a single role.

**Comment by shemau** [comment]
Merge complete.
