### ISSUE TITLE
Allow the COS bucket to configure allowed_ip

### ISSUE THREAD

**Issue by tyao117** [terraform-ibm-modules/terraform-ibm-cos#556]
### Description

Allow the capability to configure allowed_ip for the cos bucket in the main.tf

argument here: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cos_bucket#allowed_ip

### New or affected modules

COS module: https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/main/main.tf#L127

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@tyao117 We purposely don’t expose this legacy feature because it has been superseded by CBRs.

**Comment by ocofaigh** [comment]
Closing because allowed_ip is deprecated
