### ISSUE TITLE
Expose lock capability on buckets

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#592]
### Description

1. Expose https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cos_bucket#object_lock
2. Add a static check in the module to ensure object versioning is enabled when object lock is enabled
3. (May be done in a subsequent PR) - Expose object lock configuration https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cos_bucket_object_lock_configuration

**Comment by shemau** [comment]
Delivered, including object_lock_configuration in v8.2.0
