### ISSUE TITLE
Retention and cross-region error message

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#598]
### Description

```
module "cos" {
  resource_group_id      = module.resource_group.resource_group_id
  region                 = var.region
  cos_instance_name      = "${var.prefix}-cos"
  cos_tags               = var.resource_tags
  bucket_name            = "${var.prefix}-bucket"
  retention_enabled      = true 
}
```

This errors out with the following message.
validate_cross_region_retention = var.cross_region_location != "us" && var.retention_enabled ? tobool("Retention is currently only supported in the `US` location for cross region buckets.") : true

The issue is that at no point the call is retrying to create a cross region bucket.

**Comment by shemau** [comment]
Resolved in v8.2.2
