### ISSUE TITLE
Support for resourcekey names to be not known at apply time

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#601]
### Description

If the resource key name that is passed as an input to the module is dynamically generated, for instance to use a constructed name, apply results in the following:

![image](https://github.com/terraform-ibm-modules/terraform-ibm-cos/assets/16447795/081b1b0d-94b8-4a87-9655-dbbb45713546)

https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/f45883e7b5933de979e9ae49a987f9cbbbbc4bc4/main.tf#L77

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by shemau** [comment]
Resolve in v8.2.3
