### ISSUE TITLE
Update COS bucket DAs to support to creating KMS key in external account

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-cos#636]
Changes should go into `solutions/secure-cross-regional-bucket` and `solutions/secure-regional-bucket` only..

- Add new optional variable `ibmcloud_kms_api_key`. This should be used in a new provider block like so:
  ```
  provider "ibm" {
    alias            = "kms"
    ibmcloud_api_key = var.ibmcloud_kms_api_key != null ? var.ibmcloud_kms_api_key : var.ibmcloud_api_key
    region           = local.kms_region # this value should be parsed from the existing KMS CRN 
  }
  ```

- The `kms` module block should use the `kms` provider alias (its already set up like this in the code actually).
- Support creating cross account s2s auth policy (in KMS account):
  - if value for `ibmcloud_kms_api_key` is passed, and `skip_iam_authorization_policy` is set to false, then create a cross account s2s auth policy **in the KMS account** to allow the COS bucket reader access to the KMS instance GUID in the KMS account.
  - Ensure that if doing cross account auth policy, the `skip_iam_authorization_policy` value thats passed to the COS module itself is set to `true` since we will create the cross account one in the DA itself.
- Review all of the variable descriptions and readme markdowns to ensure its clear that it supports KMS in a different account using the `ibmcloud_kms_api_key` variable.

**Comment by kierramarie** [comment]
@ocofaigh I have found what I believe is a bug. In modules/buckets/main.tf line 10, I am getting an error. What is being passed in is the guid already. I think this code snippet it expecting the crn so is erroring when the string does not contain ":".
`"cos_guid" : element(split(":", bucket_config.resource_instance_id), length(split(":", bucket_config.resource_instance_id)) - 3)`

**Comment by kierramarie** [comment]
After discussing with Todd, it seems that the name id and crn are being used interchangeably here. Should the var description be updated to state that the existing cos crn should be passed in?

**Comment by kierramarie** [comment]
Pr has been merged. Closing issue.
