### ISSUE TITLE
Add some variable supporting documentation for COS instance DA

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-cos#664]
The `resource_keys` COS instance DA variable is a complex object type, and will be hard for consumers in Projects to know what format should be used for the values. I suggest that we add some supporting documentation for it, the same way we did [here](https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/blob/main/solutions/standard/DA-keys.md). Then we can update the variable description to point to the supporting doc

**Comment by shemau** [comment]
Completed in #667 in version 8.4.4
