### ISSUE TITLE
update `cross_region_location` variable description in the cross regional bucket DA

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-cos#671]
Remove "If specified, set the value of `region` and `single_site_location` to `null`." from here -> https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/3cec7c56215fbe6892791e9e31ed6a47bb5e4244/solutions/secure-cross-regional-bucket/variables.tf#L78

These vars are not in this DA

**Comment by shemau** [comment]
Complete in #675 version 8.8.5
