### ISSUE TITLE
A new COS instance is getting created even when value passed in for `existing_cos_instance_id`

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-cos#697]
A new COS instance is getting created even when value passed in for `existing_cos_instance_id` because `create_cos_instance` is set to true. To prevent this, we should add validation that does not allow `create_cos_instance` to be true if a value is being passed for `existing_cos_instance_id`

**Comment by Khuzaima05** [comment]
PR merged, Closing this issue
