### ISSUE TITLE
Optional Bucket Creation

### ISSUE THREAD

**Issue by daniel-butler-irl** [terraform-ibm-modules/terraform-ibm-cos#70]
### Description

Most of the time we want to create a bucket when creating a COS instance. But this is not always the case. Make bucket creation optional

### New or affected modules
https://github.com/terraform-ibm-modules/terraform-ibm-cos

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
This was done in https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/69
