### ISSUE TITLE
Remove `ibm_iam_account_settings` from COS module

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-cos#742]
The `ibm_iam_account_settings` data lookup requires admin account privileges, so we should avoid using when we can.

In the [secure-cross-regional-bucket](https://github.com/terraform-ibm-modules/terraform-ibm-cos/tree/23015b6dc2a87709171e15d310f8a49c7cf95737/solutions/secure-cross-regional-bucket) and [secure-regional-bucket](https://github.com/terraform-ibm-modules/terraform-ibm-cos/tree/23015b6dc2a87709171e15d310f8a49c7cf95737/solutions/secure-regional-bucket) DAs its used to get account IDs however the account ID can be parsed (using our [CRN parser module](https://github.com/terraform-ibm-modules/terraform-ibm-common-utilities/tree/main/modules/crn-parser)) from the COS instance ID which is passed in to these DAs as an input.

~As part of this effort I think it might help consuming modules if there was an account ID output for the modules, and applicable submodules~ done in https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/743

**Comment by Soaib024** [comment]
PR merged - closing the issue
