### ISSUE TITLE
COS Instance Name Added to DA Outputs

### ISSUE THREAD

**Issue by daniel-butler-irl** [terraform-ibm-modules/terraform-ibm-cos#745]
The COS instance name is generated by the DA from the `<prefix>-<name>` we should add this to the DA outputs.

**Comment by arya-girish-k** [comment]
cc : @SarikaSinha

**Comment by arya-girish-k** [comment]
PR Got merged.Hence Closing the issue.

**Comment by ocofaigh** [comment]
@arya-girish-k FYI, its a good practise to link the PR and issue (I think you linked to the internal issue in the PR but not this one. Ideally link it to the public facing issue)

**Comment by arya-girish-k** [comment]
@ocofaigh : Ok,I will update it.Thanks
