### ISSUE TITLE
Allow naming of cos instance created by terraform-ibm-cos

### ISSUE THREAD

**Issue by shemau** [terraform-ibm-modules/terraform-ibm-cos#82]
# Description

Most of the time we want to create a Cloud Object Storage instance with a predetermined name that adheres to a projects naming conventions.

The current behaviour when creating a COS instance is to use the name `environment-name`-cos. 

## New or affected modules

https://github.com/terraform-ibm-modules/terraform-ibm-cos

## Other considerations

Existing consumers of this module that specify both `create-cos-instance`=true and `cos-instance-name` may see a change in behaviour. The current behaviour is to silently ignore the `cos-instance-name` provided. The new behaviour will be to change the name of the COS instance, which may result in an attempt to delete and re-create the instance.

**Comment by ocofaigh** [comment]
Addressed in https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/99

**Comment by ocofaigh** [comment]
PR merged - closing
